import { pgTable, text, timestamp } from 'drizzle-orm/pg-core'
import { uuidv7 } from 'uuidv7'

export const uploads = pgTable('uploads', {
	id: text('id')
		.primaryKey()
		.$defaultFn(() => uuidv7()), // Primary key, UUID generated by default
	name: text('name').notNull(), // Name field, required
	remoteKey: text('remote_key').notNull().unique(), // Remote key, required and unique
	remoteUrl: text('remote_url').notNull(), // Remote URL, required
	createdAt: timestamp('created_at', { withTimezone: true }) // Timestamp with timezone
		.defaultNow()
		.notNull(), // Defaults to current time, required
})
